services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  bot_handler:
    build:
      context: ./bot_handler
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
        - ./ImagesData:/ImagesData
    depends_on:
      - redis

  image_generator:
    build:
      context: ./image_generator
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
        - ./ImagesData:/ImagesData
    depends_on:
      - redis
    